FROM alpine:latest

WORKDIR /app

COPY app.sh .

# RUN chmod +x app.sh

# Fix Windows line endings + permission
# RUN sed -i 's/\r$//' app.sh && chmod +x app.sh

RUN sed -i 's/\r$//' app.sh && \
    chmod +x app.sh && \
    mkdir -p /data

CMD [ "./app.sh" ]